apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
   server:
   email:
   privateKeySecretRef:
    name: letsencrypt-prod
   https:  { }
    